plugin:
  debug: false
  delay: 10
  omit-player-death: false
  disable-filter-network: false
  apply-null-userdata: false

kick-load-failed: true

message:
  kick_load: Your game data loading error, please contact the operator